### ISSUE TITLE
how to use makefile

### ISSUE THREAD

**Issue by palettis** [KULeuven-COSIC/HEAT#4]
I don't know how to use makefile with 'make open'
I'm using vivado 2019.1 windows, and where to use 'make open' command, in windows cmd or xilinx software command line tool, or others?

Looking forward to your help!

**Comment by furkanturan** [comment]
I don't know if there is a way to use a Makefile on Windows. I would recommend you to search for this on Google. 

If you cannot use the Makefile, I would recommend you to look into the file's content. It is a very simple one. Each make target is just a single line of terminal command. For example, `make open` will just issue a command for opening Vivado with (the previously created) project using its .xpr file. Alternatively, you can open the project (the .xpr file) from Vivado GUI, once you open it on Windows/Linux as well. For the `make build` target, what the Makefile does is to make Vivado execute `build_ipcore_interfacer.tcl` and `build_project.tcl` scripts. Again, you can handle these steps without the Makefile. You can make Vivado execute a TCL code using the TCL console.

Regards,

Furkan

**Comment by palettis** [comment]
> I don't know if there is a way to use a Makefile on Windows. I would recommend you to search for this on Google.
> 
> If you cannot use the Makefile, I would recommend you to look into the file's content. It is a very simple one. Each make target is just a single line of terminal command. For example, `make open` will just issue a command for opening Vivado with (the previously created) project using its .xpr file. Alternatively, you can open the project (the .xpr file) from Vivado GUI, once you open it on Windows/Linux as well. For the `make build` target, what the Makefile does is to make Vivado execute `build_ipcore_interfacer.tcl` and `build_project.tcl` scripts. Again, you can handle these steps without the Makefile. You can make Vivado execute a TCL code using the TCL console.
> 
> Regards,
> 
> Furkan

Thank you very much!
It is helpful . I will try it again.

Regards,

Palettis
